name: dreamflow
description: "A DreamFlow project"
publish_to: 'none'
version: 1.0.0

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.0
  fl_chart: 0.68.0
  google_fonts: 6.1.0
  shared_preferences: 2.3.2
  path_provider: 2.1.4
  provider: 6.1.2
  http: '>=1.0.0'
  uuid: '>=3.0.0'
  supabase_flutter: '>=1.10.0'
  web_socket_channel: ^3.0.0
  crypto: ^3.0.0
  agora_rtc_engine: ^6.0.0
  image: ^4.0.0

  socket_io_client: ^2.0.3+1
  permission_handler: ^11.3.1
  wakelock_plus: ^1.2.5
  flutter_stripe: ^10.1.1
  url_launcher: ^6.0.0
  intl: ^0.19.0
  shimmer: ^3.0.0
  cached_network_image: ^3.3.1
  timeago: ^3.0.0
  image_picker: '>=1.1.2'

dev_dependencies:
  flutter_test:
    sdk: flutter
  change_app_package_name: ^1.4.0

flutter:
  uses-material-design: true
